# Enunciado de ejemplo


Adiós a las listas de listas de Python...
¡Bienvenidos arreglos de la librería Numpy!

El propósito es introducir aspectos básicos de Numpy.

Como ilustración manejaremos los resultados de los partidos de la fase de grupos de la copa América 2024, en particular, del grupo D.
En el grupo D hay varios equipos (Colombia, Brasil, Paraguay y Costa Rica), cada equipo juega contra cada uno de los otros equipos una sola vez.

La información de los países representados por los equipos se puede almacenar en un arreglo unidimensional.
El tablero de goles de los partidos se puede almacenar en un arreglo bidimensional (matriz) como el que se muestra a continuación:

![Tablero goles](tablero2.png)

Note que la diagonal principal de la matriz está llena de -1 para representar que un país no puede jugar contra sí mismo.
El -2 significa que el partido no ha sido jugado, por ej., hipotéticamente Colombia y Brasil.

En las celdas donde aparezca la palabra "TODO" esperamos que resuelvas un ejercicio... ¡anímate!

# Librería Numpy

* Apareció por primera vez en 2006 y es la implementación de arreglos preferida de Python.
* Su principal estructura de datos es un arreglo n-dimensional de alto rendimiento y ricamente funcional llamado ndarray.
* Está escrita en C.
* Excelente uso de la memoria.
* Los algoritmos que se ejecuten sobre estos arreglos son más rápidos comparados con las listas.
* [Documentación oficial de NumPy](https://numpy.org/doc/)

In [1]:
import numpy as np # para usar numpy debemos empezar por importarla

## Crear arreglos Numpy

Hay varios mecanismos para crear arreglos:
* Convertir otras estructuras Python (i.e., listas)
* Utilizando funciones de creación intrínsecas de Numpy (por ej., ones, zeros, etc.)
* Etc.
* Más información sobre [Creación de arreglos](https://numpy.org/doc/stable/user/basics.creation.html)

In [2]:
# Construye un arreglo numpy "paises" que contenga los nombres de los países del grupo D
grupo_d = np.array(["Colombia","Brasil","Costa Rica","Paraguay"]) 

In [3]:
# Define una variable global "num_equipos" que almacene el número de equipos del grupo D
num_equipos = grupo_d.size

Por defecto, los elementos de un arreglo Numpy son del mismo tipo. 

In [4]:
grupo_d.dtype # este atributo nos dice el tipo de un arreglo

dtype('<U10')

Más información sobre [tipos de datos Numpy](https://numpy.org/doc/stable/user/basics.types.html)

## Recorrer matrices Numpy

In [11]:
def crear_matriz_goles(num_equipos:int)->np.array:
    
    matriz = np.array ([[-2,-2,-2,-2],
                        [-2,-2,-2,-2],
                        [-2,-2,-2,-2],
                        [-2,-2,-2,-2]], dtype=np.int8)
    
    for i in range (num_equipos):
        matriz[i][i] = -1         
                
    return matriz   

tablero = crear_matriz_goles (num_equipos)

## Actualizar valores de matriz

In [12]:
"""
TODO
Esta función carga los resultados de los partidos jugados por el grupo D en la matriz "tablero", completa el marcador que falta (te puedes fijar
la imagen del enunciado)
"""
def cargar_goles (matriz:np.array) :
    
    # Colombia --> Paraguay
    matriz[0][3] = 2
    # Paraguay --> Colombia
    matriz[3][0] = 1
    
    # Colombia --> Costa Rica
    matriz[0][2] = 3
    # Costa Rica --> Colombia
    matriz[2][0] = 0
        
    # Colombia --> Brasil
    matriz[0][1] = 1
    # Brasil --> Colombia
    matriz[1][0] = 1
    
    # Brasil vs. Costa Rica
    matriz[1][2] = 0 
    matriz[2][1] = 0
    
    # Brasil vs. Paraguay
    matriz[1][3] = 4
    matriz[3][1] = 1
    
    # ¿Paraguay vs. Costa Rica?
    
cargar_goles (tablero)

In [13]:
tablero

array([[-1,  1,  3,  2],
       [ 1, -1,  0,  4],
       [ 0,  0, -1, -2],
       [ 1,  1, -2, -1]], dtype=int8)

In [14]:
# Intenta almacenar en la matriz tablero un valor con un tipo de dato diferente, ¿se puede?

tablero[1][1] = "Cualquier valor"

ValueError: invalid literal for int() with base 10: 'Cualquier valor'

## Leer valores de matriz

In [15]:
"""
TODO
Obtén el valor del marcador del partido Brasil vs. Paraguay almacenado en la matriz "tablero"
"""

'\nTODO\nObtén el valor del marcador del partido Brasil vs. Paraguay almacenado en la matriz "tablero"\n'

## Eliminar valores de matriz

In [16]:
# Suprime Brasil del grupo
tablero_c = np.delete(tablero, 1, axis=0) # axis=0 representa a la columna
tablero_c = np.delete(tablero_c, 1, axis=1) # axis=1 representa a la fila
tablero_c

array([[-1,  3,  2],
       [ 0, -1, -2],
       [ 1, -2, -1]], dtype=int8)

## Atributos y operaciones sobre arreglos Numpy

### Atributos básicos

In [17]:
tablero.ndim # número de dimensiones del arreglo

2

In [18]:
tablero.shape # tupla especificando las dimensiones del arreglo

(4, 4)

### Operaciones de llenado con valores específicos

Las funciones `zeros`, `ones`, `full` crean arreglos conteniendo 0s, 1s, o un valor específico, respectivamente

In [19]:
np.zeros (5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones((2, 4), dtype=int) # retorna una matriz llena de 1s con las dimensiones especificadas 

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [22]:
"""
TODO
Reescriba el método crear_matriz_goles para poblar la matriz con -2 usando "full"
"""

'\nTODO\nReescriba el método crear_matriz_goles para poblar la matriz con -2 usando "full"\n'

In [23]:
tablero

array([[-1,  1,  3,  2],
       [ 1, -1,  0,  4],
       [ 0,  0, -1, -2],
       [ 1,  1, -2, -1]], dtype=int8)

### Reformando arreglos multidimensionales

El método `reshape` transforma un array en un número diferente de dimensiones.
La nueva forma debe tener el mismo número de elementos que la original, de otro modo genera error

In [24]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz = matriz.reshape(3,2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

## Operaciones de álgebra lineal

Algunas de estas funciones son: `dot` (producto punto de dos arreglos), `inner` (producto interno de dos vectores), `outer`, (producto externo de dos vectores), entre otras.

El resultado del producto punto de dos arreglos unidimensionales es el mismo que del producto interno.
El resultado del producto punto de dos arreglos bidimensionales es equivalente a la multiplicación de matrices.

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

## Operadores aritméticos sobre arreglos Numpy

* Realizan operaciones en todo el arreglo.
* Pueden realizar operaciones aritméticas entre arreglos y valores numéricos escalares, y entre arreglos.
* tablero * 2 equivale a tablero * [2] y a tablero * [[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]] ya que "tablero" es una matriz de 4 * 4 elementos.
* La réplica automática de los datos (en este caso el hecho de "estirar" [2] para tener una matriz de las misma forma y tamaño de "tablero") es posible gracias a la técnica denominada _propagación_ (_broadcasting_ en inglés).


In [26]:
tablero * 2 # aquí no se actualiza tablero, se crea uno nuevo

array([[-2,  2,  6,  4],
       [ 2, -2,  0,  8],
       [ 0,  0, -2, -4],
       [ 2,  2, -4, -2]], dtype=int8)

In [27]:
tablero ** 3

array([[-1,  1, 27,  8],
       [ 1, -1,  0, 64],
       [ 0,  0, -1, -8],
       [ 1,  1, -8, -1]], dtype=int8)

In [28]:
tablero += 1 # aquí se actualiza tablero porque hay una asignación
tablero

array([[ 0,  2,  4,  3],
       [ 2,  0,  1,  5],
       [ 1,  1,  0, -1],
       [ 2,  2, -1,  0]], dtype=int8)

Para que el broadcasting funcione entre arreglos, las dimensiones de estos arreglos deben ser _compatibles_, es decir: 
* Las dimensiones deben ser iguales o una de ellas debe ser 1. Si una dimensión es 1, se "estira" para que coincida con la otra dimensión.
* Si los arreglos tienen diferente número de dimensiones, el arreglo con menos dimensiones se rellena con los mismos datos que ya tiene.

In [29]:
"""
la operación que sigue es posible porque la forma de "a" es (1,3) y la de "b" es (3, 1). Entonces, los datos de "a" se proyectan 
hacia abajo y los de "b" hacia la derecha así:
a: [[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]]

b: [[4, 4, 4],
    [5, 5, 5],
    [6, 6, 6]]
"""
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])
resultado = a+b
resultado

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

## Comparación de matrices con valores individuales y con otras matrices

* Las comparaciones se realizan elemento por elemento
* Produce matrices de valores booleanos en las que el valor Verdadero o Falso de cada elemento indica el resultado de la comparación
* También se aplica la técnica de propagación

In [30]:
a < b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Métodos de cálculo Numpy

* Estos métodos ignoran la forma del arreglo y utilizan todos los elementos en el cálculo.
* Puede utilizar métodos para calcular `sum, min, max, mean, std` (desviación estándar) y `var` (varianza)
* La invocación de estos métodos es similar a como se hace en programación funcional 

In [31]:
notas = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [32]:
notas.min()

70

In [33]:
"""
TODO
Implemente la función total_goles que calcule el total de goles que se han marcado en el campeonato. 
La función recibe como parámetro el tablero de goles y retorna el número total de goles.
Recuerde que la diagonal principal tiene -1, indicando que un país no juega con sí mismo.
Use el método np.sum de Numpy.
"""

'\nTODO\nImplemente la función total_goles que calcule el total de goles que se han marcado en el campeonato. \nLa función recibe como parámetro el tablero de goles y retorna el número total de goles.\nRecuerde que la diagonal principal tiene -1, indicando que un país no juega con sí mismo.\nUse el método np.sum de Numpy.\n'

### Cálculos por fila o columna

* Puede realizar cálculos por columna o fila (u otras dimensiones en matrices con más de dos dimensiones)
* En un arreglo 2D, axis=0 indica que los cálculos deben realizarse columna a columna
* En un arreglo 2D, axis=1 indica que los cálculos deben realizarse fila a fila

In [ ]:
notas.mean (axis=0)

In [ ]:
"""
TODO
Implemente una función goles_pais que calcule el total de goles que se ha marcado un país en el campeonato. 
La función recibe como parámetro el tablero y el índice que tiene el país en el arreglo "países".
Retorna los goles marcados por ese país.
Use el método np.sum por fila o columna, usted debe decidir cuál de los dos es el más acertado.
Invoque el método para saber cuántos goles marcó Colombia en el grupo D
"""

Más información sobre [métodos de cálculo Numpy](https://numpy.org/doc/stable/reference/arrays.ndarray.html)